SELECT TITULOID AS "CODIGO DEL LIBRO",
COUNT(PRESTAMOID) AS "TOTAL DE VECES SOLICITADO",
CASE
    WHEN COUNT (PRESTAMO.PRESTAMOID) = 1 THEN 'No se requiere nuevos ejemplares'
    WHEN COUNT (PRESTAMO.PRESTAMOID) BETWEEN 2 AND 3 THEN 'Se requiere comprar 1 nuevos ejemplares'
    WHEN COUNT (PRESTAMO.PRESTAMOID) BETWEEN 4 AND 5 THEN ' Se requiere comprar 2 nuevos ejemplares'
    WHEN COUNT (PRESTAMO.PRESTAMOID)>5 THEN 'Se requiere comprar 4 nuevos ejemplares'
END AS "SUGERENCIA"    
FROM PRESTAMO
WHERE TO_CHAR(FECHA_INI_PRESTAMO,'YYYY')= TO_CHAR(SYSDATE,'YYYY')-1
GROUP BY TITULOID
ORDER BY COUNT(PRESTAMOID)DESC;
